name: Push Deployment to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Deploy Files to EC2
      uses: easingthemes/ssh-deploy@v4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "build/"
        target: ${{ secrets.EC2_TARGET }}

    - name: Upload Nginx Config
      uses: easingthemes/ssh-deploy@v4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "nginx-react.conf"
        target: "/etc/nginx/sites-available/"

    - name: Activate Nginx Config
      run: |
        ssh -i ${{ secrets.EC2_KEY }} \
        ${ { secrets.EC2_USER } }@${ { secrets.EC2_HOST } } \
        "sudo ln -sf /etc/nginx/sites-available/nginx-react.conf /etc/nginx/sites-enabled/nginx-react.conf && sudo nginx -t && sudo systemctl restart nginx"
